Repository ibsa-abraham-a2sv/aastu-socialmedia-api-team-2, pull requests merged in 2023-08, with the labels that each got.

#12 Fix(AASTU - Backend Team 2): Remove Validation until feature build
  src/Core/Application/DTOs/Follows/Validators/FollowsDtoValidator.cs
Labels: bug, AASTU, Backend

#13 Add(AASTU-backend-2) User unit testing
  src/Api/Api/Controllers/ProfileManager.cs
  src/Api/Api/appsettings.json
  src/Core/Application/Contracts/Identity/IUserService.cs
  src/Core/Application/Contracts/Persistence/IUnitOfWork.cs
  src/Infrastructure/Identity/IdentityServicesRegistration.cs
  src/Infrastructure/Identity/Services/UserService.cs
  tests/UnitTests/Mocks/MockUnitOfWork.cs
  tests/UnitTests/Mocks/MockUserServices.cs
  tests/UnitTests/UnitTests.csproj
  tests/UnitTests/Users/AuthServicesTest.cs
Labels: AASTU, Backend, Team 2

#14 fix(follow): add validation for followsDto
  src/Api/Api/Controllers/FollowsController.cs
  src/Core/Application/DTOs/Follows/Validators/FollowsDtoValidator.cs
  src/Core/Application/Features/Follows/Handlers/Commands/CreateFollowingRequestHandler.cs
  tests/UnitTests/Follows/Commands/CreateFollowingRequestHandlerTest.cs
Labels: bug, AASTU, Backend, Team 2
